services:
  car-database:
    image: "postgres:13-alpine"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=car-database"
    volumes:
      - "car-db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  car-db-data:

